import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nikolaj Reibke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Nikolaj Reibke
        </h1>

        <p className={styles.description}>
          The site of a Software Engineering proffesional
        </p>

        <div className={styles.grid}>
          <a href="projects" className={styles.card}>
            <h2>Personal Projects &rarr;</h2>
            <p>Come see some personal projects, and how we are working</p>
          </a>

          <a href="activities" className={styles.card}>
            <h2>Activities &rarr;</h2>
            <p>See what activities I take an interest for in my free time</p>
          </a>

          <a href="about" className={styles.card}>
            <h2>About &rarr;</h2>
            <p>
              Learn more about me
            </p>
          </a>

          <a href="contact" className={styles.card}>
            <h2>Contact me &rarr;</h2>
            <p>If you wish to contact me, there are some channels</p>
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
